# Generated by Django 3.2 on 2023-03-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reviews', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(
                blank=True, max_length=256, verbose_name='Имя'
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(
                blank=True, max_length=256, verbose_name='Фамилия'
            ),
        ),
    ]
